name: Debug (MacOS)

on: [workflow_dispatch]

jobs:
    debug:
      runs-on: macos-latest
      steps:
        - name: Checkout Zfp
          uses: actions/checkout@v3

        - name: Setup Python
          uses: actions/setup-python@v4
          with:
            python-version: '3.x'
            architecture: x64

        - name: Install Zfpy Dependencies
          run: |
            python -m pip install cython
            python -m pip install oldest-supported-numpy

        - name: Install OpenMP
          run: |
            brew install libomp

        - name: Setup Tmate Session
          uses: mxschmitt/action-tmate@v3
